### ISSUE TITLE
Change wz_location_method to location_method

### ISSUE THREAD

**Issue by DeraldDudley** [usdot-jpo-ode/jpo-wzdx#106]
Issue name: “Change wz_location_method to location_method”
 ## Summary
If the field road_events.type is added via issue #82 the field name wz_location_method should be changed to reflect the models accommodation of multiple road event types.

 ## Proposed changes
In the case of a proposed change, provide one or a few options for moving forward.
Replace wz_location_method with location_method

**Comment by j-d-b** [comment]
This field naming is part of the metadata and is already discussed in #10. This naming should be changed with the implementation of #10 even if #82 is not approved.

**Comment by DeraldDudley** [comment]
Awesome.  Thanks @j-d-b
