### ISSUE TITLE
Add Elevation Data to All Reported Positions

### ISSUE THREAD

**Issue by davidcraig4300** [usdot-jpo-ode/jpo-wzdx#111]
New feature  —  Adding elevation data to all reported positions.  

 Changing all positional data from 2D to 3D.  

The current specification assumes a flat world with no stacking of road elements.  The real world has many instances of multiple items being stacked.  For example, the High 5 interchange in Dallas Texas has 5 levels of roads stacked on-top of each other.   Elevation data is needed to be able to correctly distinguish these different levels of roads.

Additional use cases would involve:
1. Steep inclines for temporary bypasses.  These steep inclines cannot be correctly annotated and conveyed to vehicles without elevation data.
2. Work on ramps where the beginning and ending work at at significantly different elevations.
3. Work on inclined and declined (hilly/mountainous) roads.
4. Tunnel work
5. Overpass/Underpass work
6. Stacked road work.

**Comment by DeraldDudley** [comment]
Geojson includes elevation in its position data; Please see [Section 3.1.1.](https://tools.ietf.org/html/rfc7946#section-3.1.1).

**Comment by davidcraig4300** [comment]
Derald,
 From Section 3.1.1, elevation is optional.  "A position is an array of numbers.  There MUST be two or more
   elements.  The first two elements are longitude and latitude, or
   easting and northing, precisely in that order and using decimal
   numbers.  Altitude or elevation MAY be included as an optional third
   element."

And the GeoJSON itself is optional.  

I am suggesting that elevation become mandatory/required in all positions.  Thoughts??????
Dave

**Comment by j-d-b** [comment]
Based on the reference from @DeraldDudley, since WZDx follows GeoJSON, elevation data can already by provided since WZDx v2.0. Thus no spec (or even schema) change needs to happen here.
