### ISSUE TITLE
Multiplicity values within xsd file

### ISSUE THREAD

**Issue by k-vaughn** [usdot-jpo-ode/jpo-wzdx#12]
There are inconsistencies between the full specification identifying fields as optional and the XSD file identifying values for min and max occurrences. All optional fields should have minOccurrences set to "0" in the XSD.

Also, there is inconsistency in the full spec as to whether roadRestrictions is required. It is defined as optional, but the description states "one or more", which implies it is required.

**Comment by j-d-b** [comment]
No longer relevant as of v2
