### ISSUE TITLE
Use the geoJson standard to enable the use of multiple geometries.

### ISSUE THREAD

**Issue by DeraldDudley** [usdot-jpo-ode/jpo-wzdx#21]
Consider using the geoJson standard to specify how the WZD spec will incorporate and model spatial data.  Doing so will enable the use of points, lines, and polygons which could represent streets, WZ Areas, Road Furniture, and more.
https://tools.ietf.org/html/rfc7946

**Comment by j-d-b** [comment]
Implemented in #53
