### ISSUE TITLE
Type of Work Being Done

### ISSUE THREAD

**Issue by davidcraig4300** [usdot-jpo-ode/jpo-wzdx#22]
As this data starts to become a standard across many states, there are a few items that could make it more usable to Autonomous vehicles.  The missing pieces of data are about what type of construction is occurring.   A simple boolean field that would denote if the road is architecturally changing would be very helpful to know in this era of LiDAR scanning roads.  Once this exists, the next level of fidelity would be something like 10 pre-defined typical construction projects.  i.e. 1= restriping, 2 = repaving with restriping, 3 = lane addition (and there could be the lane attribute added here for which lane is being added), 4 = new intersection, etc.   This would pave the way for a clearing house server for all US construction and would simplify the HD mapping communities workload!

**Comment by j-d-b** [comment]
I agree that this would be helpful, and proposed adding `WorkType` in PR #17.

**Comment by CraigMoore-Sea** [comment]
This could be useful but seems to push the scope of WZD beyond on it's intended function. Seem like something for future version but not v2.

**Comment by davidcraig4300** [comment]
This issue was addressed in Version 2.0 through PR#33.
