### ISSUE TITLE
Standardize Lat/Long

### ISSUE THREAD

**Issue by sghorbanian** [usdot-jpo-ode/jpo-wzdx#26]
Standardize Lat/Long (3857 vs wgs-84). We prefer to use WGS-84, as this is the common standard for this kind of information.

**Comment by sergebeaudry** [comment]
this comments looks to support issues #15   [https://github.com/usdot-jpo-ode/jpo-wzdx/issues/15](url)

**Comment by sghorbanian** [comment]
satisfied by #16
