### ISSUE TITLE
Use Verified lat/long and time rather than estimated.

### ISSUE THREAD

**Issue by sghorbanian** [usdot-jpo-ode/jpo-wzdx#27]
We would prefer we have a single lat/lon field with an optional parameter to specify true if the location has been verified. Otherwise we have to check both and have no guarantee of which one is more up-to-date. I could easily see the estimated field being updated and forgetting to update the verified field as well.

**Comment by sergebeaudry** [comment]
The estimated and verified have both a play in the game.
 The verified is the final, real-time, accurate position of the work zone. Either generated by a human or by some algorithms
The estimated could be used for others purposes like Workzone position sensor in the field broadcasting its GPS position. Fixed GPS are not perfectly accurate and could transmit a position that is off by 50-100 feet once in a while and its position typically shift over time by inches or feet.  in that case the estimated could help to decide on the verified one.

**Comment by Polly-Okunieff** [comment]
In the current event data feeds, time and location may be haphazardly assigned. The intention of specifically assigning a flag on the data is to ensure that the position and times were measured and verified. A work zone may be planned to start at 10 am every day, but on some days it starts at 9:30 and others -- if it is raining, the work zone may not actually start until after the rain stops.  A work zone may be planned to be located at a certain point, but when the crew puts out the cones, they are half a mile upstream from where they were assigned to start. There is significant ambiguity in the data that currently exists.  To reduce ambiguity, the "demarcations" for time and location should be mandatory.

**Comment by j-d-b** [comment]
This is implemented in v2, through #53 and #54, which essential provide exactly what @sghorbanian is looking for, a separate field (`beginning_accuracy` and `ending_accuracy`) indicating if the coordinates are verified or estimated.
