### ISSUE TITLE
roadDirection is not always going to be clear - need heading and directionality

### ISSUE THREAD

**Issue by sghorbanian** [usdot-jpo-ode/jpo-wzdx#28]
In order for robots to reason about an obstruction best, it should know the heading and directionality of the blockage.

road direction specification"roadDirection" is not always going to be clear. There are roads that canonically go N-S but have jogs in them of E-W. Relying on direction could be inconsistent, especially if entered manually. I think it would be ideal if we could get a heading angle instead (North = 0deg) that aligned with the direction of traffic being affected. That would ensure that we could us the lat/lon and road name to validate the location and direction directly.

**Comment by sergebeaudry** [comment]
I'm feeling the opposite for the same reasons as you mentioned.   The NB, SB, EB, WB are standard naming for US roads and help to indicate in which direction is the traffic flow regardless of the real heading angle which as you mentioned could be totally misleading.    just look at this road US60 that is going in all direction https://www.google.com/maps/place/Lexington,+VA+24450,+USA/@37.7302115,-79.3186635,15z/data=!4m5!3m4!1s0x884cc8d057b0a5e5:0xe81881d4e2830060!8m2!3d37.7840208!4d-79.4428157

**Comment by sknick-iastate** [comment]
I agree with @sergebeaudry but I also see the issue @sghorbanian brings up with manual entry.  I know in Iowa if someone is manually entering the direction it is highly dependent on where they are located along the roadway and they don't consider the standard naming that Serge mentioned.  We probably need to clarify how the "roadDirection" is derived.

Also would this be resolved if we included the geometry like in pull request #40 ?

**Comment by CraigMoore-Sea** [comment]
Does the use of a polyline geometry solve this problem?

**Comment by j-d-b** [comment]
I believe the `geometry` property implemented with GeoJSON solves much of this issue, but as @sknick-iastate suggested, the `direction` property description should clarify that the `direction` is based on "standard naming for US roads" to "indicate the direction the traffic flow regardless of the real heading angle". I will create a PR to add this text to the `direction` property description on the road event entity.

**Comment by j-d-b** [comment]
Resolved in #77
