### ISSUE TITLE
Data SLA's

### ISSUE THREAD

**Issue by sghorbanian** [usdot-jpo-ode/jpo-wzdx#31]
data SLAs (e.g., frequency of updates, coverage, etc): hasn't been explicitly discussed, so we'd love to discuss this too. this directly impacts our decision whether to actively support/maintain an ingestion pipeline for this data

**Comment by CraigMoore-Sea** [comment]
Frequency is covered in the metadata. Does this not work for you?

How would you define coverage? I see it having to be defined at the network level since jurisdictional authority often overlaps, especially between the state and local levels.

**Comment by sghorbanian** [comment]
by coverage here we were referring to the number of blockages within an operational domain (eg. if there are very few, we have less interest in supporting/maintaining an ingestion pipeline.)

additionally, do we expect the "Datafeed-frequency-update" to be a one time static estimate of how often the producer is planning to update the feed, or is it more dynamic in nature?

**Comment by CraigMoore-Sea** [comment]
I don't see coverage the way you specify being something an agency can predict; it will vary over time.

"Datafeed-frequency-update" is how often the producer updates the feed. This does not mean there are necessarily changes with every update. This defines the shortest interval at which a consumer can hit the data an expect changes.

The header includes a modified date/time stamp, which can be used by consumers to determine when the feed was last modified.

**Comment by j-d-b** [comment]
Close for lack of discussion. @sghorbanian feel free to open if you have additional comments.
