### ISSUE TITLE
Additional Data types

### ISSUE THREAD

**Issue by sghorbanian** [usdot-jpo-ode/jpo-wzdx#32]
data types: although the focus of the workshop was WorkZone data, a few one-off discussions between producers and consumers described other types of data that might be worthwhile, such as bike zone, sidewalks, etc. These are also important to SDV companies in general.

**Comment by j-d-b** [comment]
@sghorbanian are you talking about types of road events? i.e. could this be implemented by adding an `event_type` field to the road event entity, which indicates the type of road event, e.g. "work zone" or "sidewalk"?

**Comment by j-d-b** [comment]
`sidewalk` and `bike-lane` are currently lane type options. Additionally, the "road event" nomenclature in v2.0 was intended to broaden the use of the concept. If you feel that your original issue is still valid please comment and we can re-open this.
