### ISSUE TITLE
Multiple lane type enumerations

### ISSUE THREAD

**Issue by sknick-iastate** [usdot-jpo-ode/jpo-wzdx#4]
For the openLanes and closedLanes fields, how can multiple lane type enumerations be used? For example on a three lane roadway, if we have a center lane closed that would leave the left lane and right lanes open.  Based on the enumerations the closedLanes=middle-lane and the openLanes =left-lane and right-lane.  The specification currently does not allow for the ability to have multiple lane type enumerations.

**Comment by CraigMoore-Sea** [comment]
I agree this is an issue. It may be solved by changing this to a list format or a nested set of lanes. I do think we need to consider that many organizations won't be able to provide this level of resolution but would still like to denote reduced capacity. We should think about to to communicate this information maybe with a higher level attribute.

**Comment by sknick-iastate** [comment]
Resolved in v2.0 PR #57
