### ISSUE TITLE
Redesign the startDateTime and EndDateTime Data Frames to facilitate translating the WZDx specification into the geoJson specification

### ISSUE THREAD

**Issue by DeraldDudley** [usdot-jpo-ode/jpo-wzdx#42]
Issue name: Redesign the startDateTime and EndDateTime Data Frames to facilitate translating the WZDx specification into the geoJson specification.

 ## Summary
The startDateTime and endDateTime Data Frames in Version 1.0 of WZDx specification are difficult to translate into the geoJson specification because the fields are not normalized. Specifically, startDateTime-est, startDateTime-ver, startDateTime-cancelled, endDateTime-est, endDateTime-ver, and endDateTime-cancelled, all contain data elements in the field name. To normalize the data, and thus ease the translation from WZDx to geoJson, I suggest the changes below.

 ## Motivation
Work Zone Data is inherently spatial and temporal.  By facilitating the use of the geoJson format publishers and consumers can leverage Geographic Information Systems and spatially enabled applications to quickly and easily visualize WZD information.

Normalizing the data simplifies the specification:  By replacing the startDatetime-ver, startDateTime-est, startDateTime-cancelled, endDatetime-ver, endDateTime-est, endDateTime-cancelled fields with the startDateTime, endDateTime, startDateTimeAccuracy, and endDateTimeAccuracy fields we reduce the needed fields from 6 to 4.

Normalizing the data eases data retrieval:  Custom computer code won’t have to be written to extract the date/time accuracy assessments from 6 different field names.  Also, it makes the data easily retrieved from the common core table instead having to write code to parse it from a separate data frame.

 ## Proposed changes
1. Abolish the StartDateTime to and EndDateTime Data Frames 
2. Include StartDateTime and EndDateTime fields as data elements in the Common Core Table
3. Create startDateTimeAccurracy and endDateTimeAccurracy fields as data elements in Common Core 
4. Include the values "Estimated" and "Verified" to describe StartDateTimeAccuracy and endDateTimeAccurracy.
5. Exclude the value “Canceled” from the Date/Time Accuracy enumeration because it indicates the status of a Work Zone and not a measure of how accurate the date/time value is.

Data Name | Data Type | Data   Description | Conformance | Notes
-- | -- | -- | -- | --
startDateTime | DateTime | The time and date when is a work zone is established | Required | All date/time formats shall use ISO 8601   Data elements and interchange formats – Information interchange –   Representation of dates and times to represent date and time data elements.
startDateTimeAccuracy | Enum   (Verified, Estimated) | A measure of how accurate the provided   Date/Time is. | Required |  
endDateTime | DateTime | The time and date when is a work zone is removed | Required | All date/time formats shall use ISO 8601   Data elements and interchange formats – Information interchange –   Representation of dates and times to represent date and time data elements.
endDateTimeAccuracy | Enum   (Verified, Estimated) | A measure of how accurate the provided   Date/Time is. | Required |

**Comment by sergebeaudry** [comment]
> endDateTime	The planned time and date when a work zone starts

you probably means "when a work zone **ends**" in the description

**Comment by Polly-Okunieff** [comment]
WZDx v1.1 included a confidence level. Confidence is different than accuracy.  Further, the original included information on whether the location and time were verified, that is confirmed that the time and location were measured (actual work began at a certain time).  These concepts are not represented in the updated version of this data frame.

**Comment by j-d-b** [comment]
Implemented as proposed here in v2 release.
