### ISSUE TITLE
Mobility Impact as a Higher Level Attribute

### ISSUE THREAD

**Issue by CraigMoore-Sea** [usdot-jpo-ode/jpo-wzdx#43]
The specification needs a way to communicate mobility impact at a work zone record level when lane level impacts are not available.

**Summary**
The current spec codes mobility impacts using the required element of lanes closed. This element has allowed values of all or none but requires data creators to produce lane specific data to enumerate partial closures.

**Motivation**
Many infrastructure owner and operators (IOOs) are unable to produce lane specific data about closures so requiring this is a barrier to adoption. Such IOOs are likely to be able to describe a mobility impact for the entire work zone record.

**Proposed changes**
There are a two options that should be discussed that can solve this issue
1. Add a new enumerated element named Mobility Impact to the Common Core Data
    - Values for this element would be: Impacted, Closed, None
2. Remove the closedLanes and openLanes elements and replace them with a new data frame named Mobility Impact
    - a new element named General Mobility Impact would be conditionally required unless one or more enumerated lane types are listed. It would have values of: Impacted, Closed, None
    - all the enumerated values for openLanes/closedLanes would become optional (or conditional) elements under this data frame
    - for each lane type used there would be the one of the following values: Open, Impacted, Closed, Shift Right, Shift Left

Option 2 has the benefit of solving the issues raised in #issue #5 and #issue #4 since multiple lanes could be listed within the Mobility Impact data frame, each with their own specific impact value.

I prefer option 2 since it allows for greater specificity and the impacts to individual lanes to be enumerated clearly. It also creates the framework to add more specificity to the impacts at a lane level such as width, heigth, or weight. I does present backwards compatibility issues though doesn't require any new data from current producers just a reformatting of their feeds.

**Comment by j-d-b** [comment]
It sounds like for both these options, we aren't loosing any information from the current version of the spec. Option 1 seems preferable only in that it's backwards compatible, but since we're already planning to make breaking changes to support polylines/changes to start/end locations, that isn't a priority. Thus, I support option 2 as well, as it solves the issues @CraigMoore-Sea noted.

**Comment by CraigMoore-Sea** [comment]
Added to v2 of the specification.
