### ISSUE TITLE
Question regarding N/A optional elements

### ISSUE THREAD

**Issue by Joseph-Kuenzi** [usdot-jpo-ode/jpo-wzdx#47]
**Summary**
For optional data elements such as workersPresent, reducedSpdPosted, or the enumerated field roadRestrictions, what is expected if no data is available? 
I have seen that some data producers are utilizing the text 'N/A' when there is no data for a optional data element, while others are simply leaving the data element blank, and others are omitting the enumerated element if unavailable.  

**Motivation**
I am currently undergoing the process of creating the specification plan for Oregon DOT's WZDx feed and want to ensure that it closely models and complies with other data producer's feeds for easy plug-in-play use by data consumers. 

**Desired Result**
Direction on what is the standard for these situations where data is unavailable would be appreciated. If the decision is to use the text 'N/A', or leave the element blank, or omit the element, then this should be denoted in the documentation so that data producers follow the same behavior.

**Comment by lynnerandolph** [comment]
I also foresee this as a potential issue, especially if someone later tries to use the data for metrics of some kind. Typically, an XML element is optional if not always known/required. For an enumerated field, only the enumerations should be used in which case roadRestrictions should either have "None" added to the list or it should be make optional. For the ones which are simple types (like workersPresent or reducedSpdPosted), having random values filled in does not seem like a good idea.

**Comment by j-d-b** [comment]
Closed to consolidate with #73. Please add new discussion there.
