### ISSUE TITLE
Rename `feed-content` directory name to `spec-content`

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/jpo-wzdx#68]
# Rename `feed-content` directory name to `spec-content`

The `feed-content` directory contains all information about the content of the specification, not just the feed (which is created using the spec). While `feed-content` is not incorrect, `spec-content` is more accurate.

This proposal is part of an ongoing effort to organize the GitHub repository. This naming change would require updating hyperlinks in several markdown files but doesn't change anything in the specification or output feed. Thus the change does not necessitate a bump in spec version.

**Comment by sknick-iastate** [comment]
I agree that `spec-content` is more accurate

**Comment by davidcraig4300** [comment]
I also agree that spec-content is more accurate.  I agree with this change.
