### ISSUE TITLE
Restrictions

### ISSUE THREAD

**Issue by sknick-iastate** [usdot-jpo-ode/jpo-wzdx#7]
The current specification has restrictions but does not provide any value limits to the restrictions.  This is critical information for oversize/overweight trucks and Iowa modified the specification slightly so that these values could be present in the feed.  We used the same restriction enumerations but provided an additional field for the restriction value (see screenshot example below).  In addition, it does not currently appear that multiple restriction enumeration types can be handled in the specification.  The modification we made would allow for multiple restriction types which is common.

![image](https://user-images.githubusercontent.com/25235821/53365798-b8d48300-3907-11e9-9dc1-c882ce37d8aa.png)

**Comment by Joseph-Kuenzi** [comment]
I agree with this addition of a RoadRestrictionValue to go along with the RoadRestrictionType as displayed in #7 Restrictions. Adding this data element should be relatively noncomplex and this RoadRestrictionValue can be an optional element so if data producers have this data available it can be supplied. 
Including the RoadRestrictionValue in the data feed will/can greatly benefit data consumers as it very applicable for use by connected vehicles. _Example:_ a commercial OTR driver receives the information that a work zone has a height restriction of [RoadRestrictionValue]. The driver can then make an informed route decision. 
If the driver only receives the information that there is a height restriction in place, they have no way of knowing if the restriction will affect them or not.

**Comment by sknick-iastate** [comment]
Resolved in v2 PR #57
