### ISSUE TITLE
Change Time/Spatial Enumerated Type enumerations to be lowercase, for consistency

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/jpo-wzdx#70]
# Change Time/Spatial Enumerated Type enumerations to be lowercase, for consistency

Currently, all WZDx enumerated types are all lowercase, dash delineated, except for Geometry Type (which is fine as it is defined by the GeoJSON standard) and time/spatial verification. I don't believe there is a reason that the time/spatial verification enumerated types should be capitalized, so this is unnecessarily inconsistent with the other enumerated types.

**Comment by sknick-iastate** [comment]
Agreed.  We can also remove the (-est) and (-ver) since these are no longer used.  They were previous used in v1.1 for the time and location data frames.

**Comment by j-d-b** [comment]
There are two options for implementing this in v3:

1. Change the Time/Spatial Enumerated Type values to lowercase (i.e. `estimated` and `verified`) and break backwards compatibility
2. Add two new allowed values to the Time/Spatial Enumerated Types and deprecate the uppercase versions, to be removed in a later version

1. is my preference as it's a simple change for producers and makes the v3 spec cleaner

**Comment by CraigMoore-Sea** [comment]
Agree that option 1 is simple even if it break backward compatibility.

**Comment by sknick-iastate** [comment]
This would be an easy change for Iowa to go with option 1.

**Comment by lynnerandolph** [comment]
I agree for TxDOT

**Comment by j-d-b** [comment]
For MassDOT as well, option 1 would be an easy change.

**Comment by j-d-b** [comment]
Fixed in #88
