### ISSUE TITLE
Format of "road_event_feed_info" "version" property, possible enumerated type

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/jpo-wzdx#80]
The `version` property on the `road_event_feed_info` entity is described as 

> The specification version used to create the dataset

This is a text field with no further indication of how the version should be represented, that is, `v2.0`, `V2`, `2`, `2.0`, etc.

This should be standardized, either with clarifying text + a regex in the JSON schema or by creating an enumeration for all the possible feed versions.

My choice for a format for this field would be `2` if we are going to continue release only major versions, and `2.0` if we want to consider minor releases.

**Comment by Mahsa-Ettefagh** [comment]
Comments received during the [V3 Specification Update Subgroup](https://github.com/usdot-jpo-ode/jpo-wzdx/wiki/WZDx-v3-Specification-Update-Subgroup-Meeting-Notes,-2020-04-29) meeting on 4/29/2020:

- Lynne Randolph: I'm good with major.minor
- Neil Boudreau, MassDOT: I think that makes the most sense
- Derald W Dudley: +1 for major.Minor
- Marysa Myers: Agreed, major.minor would be easiest and could avoid any inconsistencies using V, v, v., etc
- Jim Williams (INRIX): Also agree with major.minor.
- Ariel and David Craig to review the definition of major/minor versions of the specification

**Comment by j-d-b** [comment]
Resolved in #89
