### ISSUE TITLE
Require restriction type for a lane restriction

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/jpo-wzdx#81]
Currently, none of the fields on `lane_restriction` entity that are present in the output data feed are required. That means it's possible for the `lane_restrictions` field on the `lane` object to contain an array of empty objects, that is

```json
{
  "lanes": [
    {
      "lane_restrictions: [{},{}],
    }
  ]
}
```

Requiring restriction type on the lane_restriction entity would solve this issue and is a simple fix. I don't see a downside to having this required as a lane restriction is useless without the type.

**Comment by Mahsa-Ettefagh** [comment]
Comments received during the [V3 Specification Update Subgroup](https://github.com/usdot-jpo-ode/jpo-wzdx/wiki/WZDx-v3-Specification-Update-Subgroup-Meeting-Notes,-2020-04-29) meeting on 4/29/2020:

- Chris Brookes MDOT: so how would working outside the roadway be added? Tree Clearing Surveying operations? We want to show the workers on the side of the road. as this is a common work type. I just wanted to make sure that was an option as if you cant leave it blank, but sounds like it is. Chris is already part of the Worker Presence subgroup.

**Comment by j-d-b** [comment]
Added in #87
