### ISSUE TITLE
Discrepancy between the described data tables and the examples

### ISSUE THREAD

**Issue by justin-blackmon** [usdot-jpo-ode/jpo-wzdx#85]
In the `road_events` table description it refers to `types_of_work` as a separate table that has a foreign key reference of `road_event_id` to the `road_events` table. I noticed the same thing with the `lanes` table description. However, when you look at the examples `lanes` and `types_of_work` are actually nested elements of the `road_events` element, not some separate element that refers to `road_events` by a foreign key. In fact, `road_event_id` does not appear in either of the `lanes` or `types_of_work` elements themselves. See below for an example. If the examples are the correct way for the feed to look, then I think you could just add `lanes` and `types_of_work` to the `road_events` table description as type `lanes` and `types_of_work` respectively. 

`{
     "type": "Feature",
     "properties": {
       "road_event_id": "67890",
       "subidentifier": "State_Project_002",
       "road_name": "Barrett Street",
       "road_number": "I-200",
       "direction": "west bound",
       "beginning_cross_street": "King St",
       "ending_cross_street": "Hampton Garden Dr",
       "beginning_milepost": 120.10,
       "ending_milepost": 121.50,
       "beginning_accuracy": "estimated",
       "ending_accuracy": "estimated",
       "start_date": "2010-01-01T01:03:01Z",
       "end_date": "2010-01-02T01:07:01Z",
       "start_date_accuracy": "verified",
       "end_date_accuracy": "verified",
       "event_status": "completed",
       "total_num_lanes": 2,
       "vehicle_impact": "all-lanes-open",
       "workers_present": true,
       "reduced_speed_limit": 30,
       "restrictions": [],
       "description": "Dummy work zone",
       "issuing_organization": "Testco",
       "creation_date": "2010-01-01T01:01:01Z",
       "update_date": "2010-01-01T01:01:01Z",
       "types_of_work": [
         {
           "type_name": "roadside-work",
           "is_architectual_change": false
         }
       ],
       "lanes": [
         {
           "lane_edge_reference": "left",
           "lane_number": 1,
           "lane_status": "open",
           "lane_type": "left-lane",
           "lane_restrictions": [
             {
               "restriction_type": "no-trucks"
             }
           ]
         },
         {
           "lane_edge_reference": "left",
           "lane_number": 2,
           "lane_status": "open",
           "lane_type": "right-lane"
         }
       ]
     },
     "geometry": {
       "type": "LineString",
       "coordinates": [
          [
            -72.63547003269196,
            42.333474551052404
          ],
          [
            -72.63563096523285,
            42.333450757565444
          ],
          [
            -72.63599574565887,
            42.333446791983405
          ],
          [
            -72.63645708560944,
            42.33349041337203
          ],
          [
            -72.63735830783844,
            42.33354593145921
          ],
          [
            -72.63793766498564,
            42.33359748392484
          ],
          [
            -72.63901591300964,
            42.33368472646276
          ],
          [
            -72.63960599899292,
            42.33373627881463
          ],
          [
            -72.64037847518921,
            42.3337997278051
          ]
        ]
     }
   }`

**Comment by j-d-b** [comment]
The tables (in `data-tables`) detail how to structure WZED data when storing it as well as indicating the relationship between entities. The output of the WZDx feed (the GeoJSON file shown in `examples`) is built from the data stored in the tables but uses the relationship to nest entities. Thus the ID fields are often not needed or would simply be clutter on the feed output.
