### ISSUE TITLE
Define versioning rules: use Semantic Verisioning (SemVer)

### ISSUE THREAD

**Issue by j-d-b** [usdot-jpo-ode/jpo-wzdx#90]
There are not currently any versioning rules or conventions defined for WZDx. On the April 29th WZDx v3 Spec subgroup meeting, the desire for a defined versioning scheme was expressed. Having rules for versioning can illustrate what happened between WZDx versions just from the version number. 

One of the most of famous and widely used versioning rule specifications in software is the [Semantic Versioning Specification](https://semver.org/), commonly known as SemVer.

Full SemVer rules are defined at https://semver.org/ in a clear format. As a summary: 

* The version number must follow `major.minor.patch`
* The patch version must be incremented if only backwards compatible bug fixes are introduced
* The minor version must be incremented if new, backwards compatible functionality is introduced or any functionality is marked as deprecated
* The major version number must be incremented if any backwards incompatible changes are introduced

For the WZDx specification, this could look like:

* The patch version must be incremented for text documentation/business rule changes that don't affect the structure of the feed 
* The minor version must be incremented if new, backwards compatible fields/entities/enumerations are introduced or if any existing fields/entities/enumerations are marked as deprecated
* The major version number must be incremented if any backwards incompatible changes are introduced

Thus far, the WZDx specification has performed updates in bulk in long iteration cycles. Using SemVer would facilitate shorter cycles in the long term, and in the short term, even for the immediate v3 release cycle, we could perform multiple small releases subsequently at the end of the v3 update process after all PRs for v3 are approved. For example, we could introduce all the non-breaking in a minor update, followed by the breaking changes in a major update. This would provide producers with the ability to adopt backwards compatible new features without having to make the breaking changes that are part of the major release.

Even without the usage for shorter release cycles or multiple releases at the end of a cycle, defining versioning rules will be helpful and is an important part of a mature specification.

**Comment by lynnerandolph** [comment]
Those are the rules we use with our application versioning as well. I'm in favor.

Lynne

**Comment by j-d-b** [comment]
Loosely implemented in #90
